AWSTemplateFormatVersion: "2010-09-09"
Description: "Task Definition for Wallet Service"
Resources:
  MyTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      RequiresCompatibilities:
        - "FARGATE"
      ExecutionRoleArn: "arn:aws:iam::477043663148:role/ecsTaskExecutionRole"
      Cpu: 256
      Memory: 512
      NetworkMode: "awsvpc"
      ContainerDefinitions:
        - Name: "wallet-service"
          Image: "477043663148.dkr.ecr.us-east-1.amazonaws.com/dex-wallet-service:latest"
          MemoryReservation: 256
          Memory: 512
          PortMappings:
            - ContainerPort: 3000
              Protocol: tcp