services:
    wallet:
        build:
            context: ./dex-wallet
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        environment:
          - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
          - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
          - AWS_REGION=${AWS_DEFAULT_REGION}
    
    exchange-service:
        build:
            context: ./exchange-api
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        environment:
          - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
          - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
          - AWS_REGION=${AWS_DEFAULT_REGION}

    auth-service:
        build:
            context: ./dex-auth
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        environment:
          - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
          - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
          - AWS_REGION=${AWS_DEFAULT_REGION}
    